name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # allow this job to push commits
    permissions:
      contents: write

    steps:
      # 1) Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Generate the snake files
      - name: Generate Snake (SVG + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: MohammadMDX
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # 3) Commit and push to `output` branch
      - name: Push Snake to output branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
          message: "chore: update contribution snake"
