```yaml
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:       # Manual trigger from Actions tab

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write   # ✅ Allows pushing to branches
      pages: write
      id-token: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # prevents old credentials conflicts

      - name: Generate Snake SVG files
        uses: Platane/snk@v3
        with:
          github_user_name: MohammadMDX
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push Snake files to output branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Generate contribution snake animation"
          git push -f origin output
```
